<?xml version="1.0" encoding="utf-8"?><Database Name="TagThis" Class="TagThisDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\TagThis.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TagThisConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CommentRating" Member="CommentRatings">
    <Type Name="CommentRating">
      <Column Name="comment_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Comment_CommentRating" Member="Comment" ThisKey="comment_id" OtherKey="id" Type="Comment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tagmap" Member="tagmaps">
    <Type Name="tagmap">
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tag_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tagmap_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="WebPage_tagmap" Member="WebPage" ThisKey="page_id" OtherKey="page_id" Type="WebPage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PasswordReset" Member="PasswordResets">
    <Type Name="PasswordReset">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tags" Member="tags">
    <Type Name="tag">
      <Column Name="tag_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Subscriptions" Member="Subscriptions">
    <Type Name="Subscription">
      <Column Name="Subscriber" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Subscribedto" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="favs" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="loves" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscribedtoName" Type="System.String" DbType="NChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Invitations" Member="Invitations">
    <Type Name="Invitation">
      <Column Name="email" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Checked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="invitedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WebPage" Member="WebPages">
    <Type Name="WebPage">
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="AddedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="html" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thumburl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="views" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="clicks" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="WebPage_tagmap" Member="tagmaps" ThisKey="page_id" OtherKey="page_id" Type="tagmap" />
      <Association Name="WebPage_Post" Member="Posts" ThisKey="page_id" OtherKey="pageid" Type="Post" />
      <Association Name="WebPage_Comment" Member="Comments" ThisKey="page_id" OtherKey="page_id" Type="Comment" />
      <Association Name="WebPage_UserPageRelation" Member="UserPageRelations" ThisKey="page_id" OtherKey="Page_id" Type="UserPageRelation" />
    </Type>
  </Table>
  <Table Name="dbo.interestmap" Member="interestmaps">
    <Type Name="interestmap">
      <Column Name="tag_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pageid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Posts" Member="Posts">
    <Type Name="Post">
      <Column Name="pageid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RepostedFrom_postid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="User_Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Full_Name" Type="System.String" DbType="NChar(256)" CanBeNull="true" />
      <Association Name="Post_Post" Member="Posts" ThisKey="id" OtherKey="RepostedFrom_postid" Type="Post" />
      <Association Name="Post_PostUserTag" Member="PostUserTags" ThisKey="id" OtherKey="Postid" Type="PostUserTag" />
      <Association Name="Post_Comment" Member="Comments" ThisKey="id" OtherKey="postid" Type="Comment" />
      <Association Name="Post_UserPageRelation" Member="UserPageRelations" ThisKey="id" OtherKey="Post_id" Type="UserPageRelation" />
      <Association Name="Post_Post" Member="Post1" ThisKey="RepostedFrom_postid" OtherKey="id" Type="Post" IsForeignKey="true" />
      <Association Name="WebPage_Post" Member="WebPage" ThisKey="pageid" OtherKey="page_id" Type="WebPage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.notifications" Member="notifications">
    <Type Name="notification">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="recipient_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="sender_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="activity_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="object_id" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="is_read" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="date_read" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PostUserTags" Member="PostUserTags">
    <Type Name="PostUserTag">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Userid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Postid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Taggedby" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Post_PostUserTag" Member="Post" ThisKey="Postid" OtherKey="id" Type="Post" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="userid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Full_Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="postid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Comment_CommentRating" Member="CommentRatings" ThisKey="id" OtherKey="comment_id" Type="CommentRating" />
      <Association Name="Post_Comment" Member="Post" ThisKey="postid" OtherKey="id" Type="Post" IsForeignKey="true" />
      <Association Name="WebPage_Comment" Member="WebPage" ThisKey="page_id" OtherKey="page_id" Type="WebPage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserPageRelation" Member="UserPageRelations">
    <Type Name="UserPageRelation">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Page_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rate" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Post_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Post_UserPageRelation" Member="Post" ThisKey="Post_id" OtherKey="id" Type="Post" IsForeignKey="true" />
      <Association Name="WebPage_UserPageRelation" Member="WebPage" ThisKey="Page_id" OtherKey="page_id" Type="WebPage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserData" Member="UserDatas">
    <Type Name="UserData">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FBtoken" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FBid" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="FBautopost" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailFollows" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailReposts" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailLikes" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailCommentsReply" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailComments" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailCommentsLike" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailUserPostTag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>